### ISSUE TITLE
can you send the ammunation truck?

### ISSUE THREAD

**Issue by SliderKP** [CarlosVergikosk/LP_AmmuJob#1]
please :D https://forum.fivem.net/uploads/default/optimized/4X/e/0/7/e075a96b15c22cd973043816613c9d15b8231989_2_690x257.jpeg

**Comment by CarlosVergikosk** [comment]
[ammu.zip](https://github.com/CarlosVergikosk/LP_AmmuJob/files/3582222/ammu.zip)

**Comment by SliderKP** [comment]
amazing,. THANKS!
